id: P005616
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:07:20.782831
source_metadata:
  id: bdr:W1PD166109
  title: དཔལ་ལྡན་སྟག་ལུང་པའི་གསུང་རྣམས་ནོར་བཞི་བང་མཛོད།
  author: ''
  volumes:
    42a5405cb04d4503b791f53e498222d3:
      image_group_id: I3PD10
      title: ''
      volume_number: 2
      total_pages: 544
      base_file: v001.txt
    ad18dc5fa4b148ba9fcca902993c0d01:
      image_group_id: I3PD11
      title: ''
      volume_number: 3
      total_pages: 502
      base_file: v002.txt
    91c44a65f9534d62ae1e27ceedec06ab:
      image_group_id: I3PD12
      title: ''
      volume_number: 4
      total_pages: 577
      base_file: v003.txt
    83cd0fde10744f1da8dd0ff05c386cfe:
      image_group_id: I3PD13
      title: ''
      volume_number: 5
      total_pages: 648
      base_file: v004.txt
    5df4db9ce18c43fda9a501623843c109:
      image_group_id: I3PD14
      title: ''
      volume_number: 6
      total_pages: 486
      base_file: v005.txt
    31b2f75dae954f4d8ce70c155ba227ad:
      image_group_id: I3PD15
      title: ''
      volume_number: 7
      total_pages: 462
      base_file: v006.txt
    01d8b7f73877488ebf30b1df588e9f92:
      image_group_id: I3PD16
      title: ''
      volume_number: 8
      total_pages: 518
      base_file: v007.txt
    1346e41034464016bfb313cc84a40eee:
      image_group_id: I3PD17
      title: ''
      volume_number: 9
      total_pages: 508
      base_file: v008.txt
    1eb4bf806a904de09556262ceb1fcd37:
      image_group_id: I3PD18
      title: ''
      volume_number: 10
      total_pages: 478
      base_file: v009.txt
    d39493f407d24c15bf4e864a13798e4e:
      image_group_id: I3PD19
      title: ''
      volume_number: 11
      total_pages: 496
      base_file: v010.txt
    5371d50c23444a1eb1b1aef1a1a6c5f4:
      image_group_id: I3PD20
      title: ''
      volume_number: 12
      total_pages: 472
      base_file: v011.txt
    5452a412e5be4538a42b8c40e4b7fa53:
      image_group_id: I3PD21
      title: ''
      volume_number: 13
      total_pages: 454
      base_file: v012.txt
    184d76d389bc438fb91615222b1fa0da:
      image_group_id: I3PD22
      title: ''
      volume_number: 14
      total_pages: 466
      base_file: v013.txt
    d9c13d8fd6974da8b6c703dc3f304549:
      image_group_id: I3PD23
      title: ''
      volume_number: 15
      total_pages: 524
      base_file: v014.txt
    e576cffb18af4d8b99d922e209bf0b16:
      image_group_id: I3PD24
      title: ''
      volume_number: 16
      total_pages: 580
      base_file: v015.txt
    f4b64e183ff44b6494770299915ffcb0:
      image_group_id: I3PD25
      title: ''
      volume_number: 17
      total_pages: 608
      base_file: v016.txt
    468fee90d402452ba312038f82cf2682:
      image_group_id: I3PD26
      title: ''
      volume_number: 18
      total_pages: 486
      base_file: v017.txt
    6a4cdf05821a45958793e72b34b7a087:
      image_group_id: I3PD27
      title: ''
      volume_number: 19
      total_pages: 436
      base_file: v018.txt
    2d8859b2fc8d4e77ba924e2569b9fd69:
      image_group_id: I3PD28
      title: ''
      volume_number: 20
      total_pages: 466
      base_file: v019.txt
    0acd969382444a318a526bea344ba0a9:
      image_group_id: I3PD29
      title: ''
      volume_number: 21
      total_pages: 434
      base_file: v020.txt
    1f374098d6274843890f3c109552df0f:
      image_group_id: I3PD30
      title: ''
      volume_number: 22
      total_pages: 428
      base_file: v021.txt
    a83d98c8679a487a9fe0ab4a535d4b23:
      image_group_id: I3PD31
      title: ''
      volume_number: 23
      total_pages: 456
      base_file: v022.txt
    30093da58db548bf8625f3446dcc511d:
      image_group_id: I3PD32
      title: ''
      volume_number: 24
      total_pages: 386
      base_file: v023.txt
    feb3ddd0687341d7ae4dff130e9a0a7e:
      image_group_id: I3PD33
      title: ''
      volume_number: 25
      total_pages: 458
      base_file: v024.txt
    c08c2ef7464342a9b85e3c4523bbc2e3:
      image_group_id: I3PD34
      title: ''
      volume_number: 26
      total_pages: 516
      base_file: v025.txt
    37341a116ca449dbb652717621626fb9:
      image_group_id: I3PD35
      title: ''
      volume_number: 27
      total_pages: 670
      base_file: v026.txt
    a6f7f065ef874aed82dc7246a153fca1:
      image_group_id: I3PD36
      title: ''
      volume_number: 28
      total_pages: 506
      base_file: v027.txt
    d235c5ead01e484b9a9800c7e8e205e8:
      image_group_id: I3PD37
      title: ''
      volume_number: 29
      total_pages: 560
      base_file: v028.txt
    d324ffce5d4a4e72b4ba381a09f91c8c:
      image_group_id: I3PD38
      title: ''
      volume_number: 30
      total_pages: 536
      base_file: v029.txt
    492be3269c214355981aae2039242de0:
      image_group_id: I3PD39
      title: ''
      volume_number: 31
      total_pages: 500
      base_file: v030.txt
    d8a1311820b74c99b55acba719f892da:
      image_group_id: I3PD40
      title: ''
      volume_number: 32
      total_pages: 540
      base_file: v031.txt
    7d4d42c1e0af44928b473acef9d4c5ba:
      image_group_id: I3PD41
      title: ''
      volume_number: 33
      total_pages: 476
      base_file: v032.txt
    0a85845d40a34b56bd09029c91e65f61:
      image_group_id: I3PD42
      title: ''
      volume_number: 34
      total_pages: 488
      base_file: v033.txt
    962878895a264457847403b222c1c6f1:
      image_group_id: I3PD43
      title: ''
      volume_number: 35
      total_pages: 536
      base_file: v034.txt
    b3adc996d3fa4bbeb766a02cf436d6c5:
      image_group_id: I3PD44
      title: ''
      volume_number: 36
      total_pages: 508
      base_file: v035.txt
    e08acbc9c8414a9181765d8353152bac:
      image_group_id: I3PD45
      title: ''
      volume_number: 37
      total_pages: 512
      base_file: v036.txt
    2e60567df45246a6a36e57d79207da78:
      image_group_id: I3PD46
      title: ''
      volume_number: 38
      total_pages: 518
      base_file: v037.txt
    2d271bafb20f40858790493e737dc786:
      image_group_id: I3PD47
      title: ''
      volume_number: 39
      total_pages: 484
      base_file: v038.txt
    1241ae2874db4118aa63088d48541eed:
      image_group_id: I3PD48
      title: ''
      volume_number: 40
      total_pages: 592
      base_file: v039.txt
    9f78816988724573867f47bcd6c3ec3a:
      image_group_id: I3PD49
      title: ''
      volume_number: 41
      total_pages: 642
      base_file: v040.txt
    fa0a39ffd9b74cb3b4958ba38fed8f15:
      image_group_id: I3PD50
      title: ''
      volume_number: 42
      total_pages: 530
      base_file: v041.txt
    c93ff827c5264843abd9d0e659f93fe1:
      image_group_id: I3PD51
      title: ''
      volume_number: 43
      total_pages: 490
      base_file: v042.txt
    a577cba5eb4344aabb4b5788ab76e4fa:
      image_group_id: I3PD52
      title: ''
      volume_number: 44
      total_pages: 498
      base_file: v043.txt
    8408749112d34eca929f6d74844dae33:
      image_group_id: I3PD53
      title: ''
      volume_number: 45
      total_pages: 534
      base_file: v044.txt
    4cc84c0be6614375a73eb4745cf77efe:
      image_group_id: I3PD54
      title: ''
      volume_number: 46
      total_pages: 550
      base_file: v045.txt
    93fbfa84253b45aeaf3ffa7f9f621288:
      image_group_id: I3PD55
      title: ''
      volume_number: 47
      total_pages: 486
      base_file: v046.txt
    5d22c82535294258b0627797902adffb:
      image_group_id: I3PD56
      title: ''
      volume_number: 48
      total_pages: 564
      base_file: v047.txt
    cbf74f0830f54075adf919536a70f15d:
      image_group_id: I3PD57
      title: ''
      volume_number: 49
      total_pages: 540
      base_file: v048.txt
    e9014717fbda40e799ee50f60bd023f2:
      image_group_id: I3PD58
      title: ''
      volume_number: 50
      total_pages: 516
      base_file: v049.txt
    05f350773480415587001e001eb09a29:
      image_group_id: I3PD59
      title: ''
      volume_number: 51
      total_pages: 470
      base_file: v050.txt
    8d7380942bd1478dbda74cab9a7282b4:
      image_group_id: I3PD60
      title: ''
      volume_number: 52
      total_pages: 476
      base_file: v051.txt
    8195ed68641e46668325419ea20ec612:
      image_group_id: I3PD61
      title: ''
      volume_number: 53
      total_pages: 514
      base_file: v052.txt
    4acbaeca0d8047ab86a61e09179d2e6e:
      image_group_id: I3PD62
      title: ''
      volume_number: 54
      total_pages: 550
      base_file: v053.txt
    4f2c4e090cac454d9c4c1baa4e45c145:
      image_group_id: I3PD63
      title: ''
      volume_number: 55
      total_pages: 538
      base_file: v054.txt
    f66570e6386841b8b615311cd69dcda1:
      image_group_id: I3PD64
      title: ''
      volume_number: 56
      total_pages: 560
      base_file: v055.txt
    c820a61cfb52403190bf224175bc5ade:
      image_group_id: I3PD65
      title: ''
      volume_number: 57
      total_pages: 558
      base_file: v056.txt
    7855200f7b00465187f7e36092ec3d0f:
      image_group_id: I3PD66
      title: ''
      volume_number: 58
      total_pages: 536
      base_file: v057.txt
    7b324328792f467095320403eb315f3f:
      image_group_id: I3PD67
      title: ''
      volume_number: 59
      total_pages: 496
      base_file: v058.txt
    32ddc1d3232f469996e61f5ec024639c:
      image_group_id: I3PD68
      title: ''
      volume_number: 60
      total_pages: 492
      base_file: v059.txt
    33580c01700c4f02b3bb2533da00aca5:
      image_group_id: I3PD69
      title: ''
      volume_number: 61
      total_pages: 682
      base_file: v060.txt
    165d5462282e416f92963620e5605b5c:
      image_group_id: I3PD9
      title: ''
      volume_number: 1
      total_pages: 0
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
