id: ID9CF3FA5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T22:54:10+00:00'
last_modified: '2022-06-08T05:19:31.029419+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD166109
  title: དཔལ་ལྡན་སྟག་ལུང་པའི་གསུང་རྣམས་ནོར་བཞི་བང་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F8D9:
      image_group_id: I3PD9
      title: ''
      total_pages: 0
      order: 1
      base_file: F8D9.txt
    '6498':
      image_group_id: I3PD10
      title: ''
      total_pages: 544
      order: 2
      base_file: 6498.txt
    A9B8:
      image_group_id: I3PD11
      title: ''
      total_pages: 502
      order: 3
      base_file: A9B8.txt
    290A:
      image_group_id: I3PD12
      title: ''
      total_pages: 577
      order: 4
      base_file: 290A.txt
    7F7B:
      image_group_id: I3PD13
      title: ''
      total_pages: 648
      order: 5
      base_file: 7F7B.txt
    '4885':
      image_group_id: I3PD14
      title: ''
      total_pages: 486
      order: 6
      base_file: 4885.txt
    C3F4:
      image_group_id: I3PD15
      title: ''
      total_pages: 462
      order: 7
      base_file: C3F4.txt
    6FC3:
      image_group_id: I3PD16
      title: ''
      total_pages: 518
      order: 8
      base_file: 6FC3.txt
    494F:
      image_group_id: I3PD17
      title: ''
      total_pages: 508
      order: 9
      base_file: 494F.txt
    D394:
      image_group_id: I3PD18
      title: ''
      total_pages: 478
      order: 10
      base_file: D394.txt
    4F67:
      image_group_id: I3PD19
      title: ''
      total_pages: 496
      order: 11
      base_file: 4F67.txt
    1F9F:
      image_group_id: I3PD20
      title: ''
      total_pages: 472
      order: 12
      base_file: 1F9F.txt
    989B:
      image_group_id: I3PD21
      title: ''
      total_pages: 454
      order: 13
      base_file: 989B.txt
    02B0:
      image_group_id: I3PD22
      title: ''
      total_pages: 466
      order: 14
      base_file: 02B0.txt
    F9D6:
      image_group_id: I3PD23
      title: ''
      total_pages: 524
      order: 15
      base_file: F9D6.txt
    D3B1:
      image_group_id: I3PD24
      title: ''
      total_pages: 580
      order: 16
      base_file: D3B1.txt
    373D:
      image_group_id: I3PD25
      title: ''
      total_pages: 608
      order: 17
      base_file: 373D.txt
    6FF6:
      image_group_id: I3PD26
      title: ''
      total_pages: 486
      order: 18
      base_file: 6FF6.txt
    B675:
      image_group_id: I3PD27
      title: ''
      total_pages: 436
      order: 19
      base_file: B675.txt
    3BF6:
      image_group_id: I3PD28
      title: ''
      total_pages: 466
      order: 20
      base_file: 3BF6.txt
    2C47:
      image_group_id: I3PD29
      title: ''
      total_pages: 434
      order: 21
      base_file: 2C47.txt
    9CDD:
      image_group_id: I3PD30
      title: ''
      total_pages: 428
      order: 22
      base_file: 9CDD.txt
    A158:
      image_group_id: I3PD31
      title: ''
      total_pages: 456
      order: 23
      base_file: A158.txt
    B8FB:
      image_group_id: I3PD32
      title: ''
      total_pages: 386
      order: 24
      base_file: B8FB.txt
    9F19:
      image_group_id: I3PD33
      title: ''
      total_pages: 458
      order: 25
      base_file: 9F19.txt
    B77D:
      image_group_id: I3PD34
      title: ''
      total_pages: 516
      order: 26
      base_file: B77D.txt
    6C6F:
      image_group_id: I3PD35
      title: ''
      total_pages: 670
      order: 27
      base_file: 6C6F.txt
    6FBF:
      image_group_id: I3PD36
      title: ''
      total_pages: 506
      order: 28
      base_file: 6FBF.txt
    BFB4:
      image_group_id: I3PD37
      title: ''
      total_pages: 560
      order: 29
      base_file: BFB4.txt
    DFC5:
      image_group_id: I3PD38
      title: ''
      total_pages: 536
      order: 30
      base_file: DFC5.txt
    08F3:
      image_group_id: I3PD39
      title: ''
      total_pages: 500
      order: 31
      base_file: 08F3.txt
    '2014':
      image_group_id: I3PD40
      title: ''
      total_pages: 540
      order: 32
      base_file: 2014.txt
    7EB1:
      image_group_id: I3PD41
      title: ''
      total_pages: 476
      order: 33
      base_file: 7EB1.txt
    593D:
      image_group_id: I3PD42
      title: ''
      total_pages: 488
      order: 34
      base_file: 593D.txt
    D32C:
      image_group_id: I3PD43
      title: ''
      total_pages: 536
      order: 35
      base_file: D32C.txt
    '6877':
      image_group_id: I3PD44
      title: ''
      total_pages: 508
      order: 36
      base_file: 6877.txt
    '2116':
      image_group_id: I3PD45
      title: ''
      total_pages: 512
      order: 37
      base_file: 2116.txt
    645E:
      image_group_id: I3PD46
      title: ''
      total_pages: 518
      order: 38
      base_file: 645E.txt
    6CB8:
      image_group_id: I3PD47
      title: ''
      total_pages: 484
      order: 39
      base_file: 6CB8.txt
    '1523':
      image_group_id: I3PD48
      title: ''
      total_pages: 592
      order: 40
      base_file: 1523.txt
    E044:
      image_group_id: I3PD49
      title: ''
      total_pages: 642
      order: 41
      base_file: E044.txt
    14D0:
      image_group_id: I3PD50
      title: ''
      total_pages: 530
      order: 42
      base_file: 14D0.txt
    '9589':
      image_group_id: I3PD51
      title: ''
      total_pages: 490
      order: 43
      base_file: 9589.txt
    2A79:
      image_group_id: I3PD52
      title: ''
      total_pages: 498
      order: 44
      base_file: 2A79.txt
    6D20:
      image_group_id: I3PD53
      title: ''
      total_pages: 534
      order: 45
      base_file: 6D20.txt
    967C:
      image_group_id: I3PD54
      title: ''
      total_pages: 550
      order: 46
      base_file: 967C.txt
    '9363':
      image_group_id: I3PD55
      title: ''
      total_pages: 486
      order: 47
      base_file: 9363.txt
    639B:
      image_group_id: I3PD56
      title: ''
      total_pages: 564
      order: 48
      base_file: 639B.txt
    5E22:
      image_group_id: I3PD57
      title: ''
      total_pages: 540
      order: 49
      base_file: 5E22.txt
    66B4:
      image_group_id: I3PD58
      title: ''
      total_pages: 516
      order: 50
      base_file: 66B4.txt
    9E2D:
      image_group_id: I3PD59
      title: ''
      total_pages: 470
      order: 51
      base_file: 9E2D.txt
    '9724':
      image_group_id: I3PD60
      title: ''
      total_pages: 476
      order: 52
      base_file: 9724.txt
    '0732':
      image_group_id: I3PD61
      title: ''
      total_pages: 514
      order: 53
      base_file: 0732.txt
    FC99:
      image_group_id: I3PD62
      title: ''
      total_pages: 550
      order: 54
      base_file: FC99.txt
    8E36:
      image_group_id: I3PD63
      title: ''
      total_pages: 538
      order: 55
      base_file: 8E36.txt
    F402:
      image_group_id: I3PD64
      title: ''
      total_pages: 560
      order: 56
      base_file: F402.txt
    7A08:
      image_group_id: I3PD65
      title: ''
      total_pages: 558
      order: 57
      base_file: 7A08.txt
    '5530':
      image_group_id: I3PD66
      title: ''
      total_pages: 536
      order: 58
      base_file: 5530.txt
    FC8F:
      image_group_id: I3PD67
      title: ''
      total_pages: 496
      order: 59
      base_file: FC8F.txt
    6EE8:
      image_group_id: I3PD68
      title: ''
      total_pages: 492
      order: 60
      base_file: 6EE8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
